# Site settings
title: CSU Fresno Recycling Trashcan Locations
email: csaba.toth.us@gmail.com
description: The locations of recycling trashcans around the campus.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://recyclingtrashcans.github.io/" # the base hostname & protocol for your site
copyright: '&copy; 2021 Csaba Toth'

# Links
fresnostategeology: "https://www.fresnostate.edu/csm/ees/"
source_repo: "https://github.com/RecyclingTrashCans/RecyclingTrashCans.github.io/"

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: red-indigo

# Google Analytics account ID (UA-XXXXXXXX-X)
google-analytics-ua: UA-86563829-9
gmaps_yo: "AIzaSyBm7DK2d-zrF1zOOEyDpoMyLiUWwrAROuk"
main_map:
  lat: 36.814079
  lon: -119.7442877
