# Site settings
title: CSU Fresno Recycling Trashcan Locations
email: csaba.toth.us@gmail.com
description: The locations of recycling trashcans around the campus.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://recyclingtrashcans.github.io/" # the base hostname & protocol for your site
copyright: '&copy; 2021 Csaba Toth'

# Links
fresnostategeology: "https://www.fresnostate.edu/csm/ees/"

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: red-green

# Google Analytics account ID (UA-XXXXXXXX-X)
google-analytics-ua: UA-86563829-9
